src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case’s Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SuccessMessage__c</fullName>
        <label>Received Success Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <description>Custom class from HW 9</description>
    <fields>
        <fullName>ClosedCases__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Closed Cases</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SuccessMessage__c</fullName>
        <label>Success Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CaseTriggerTestFactory.cls
/**
 * Created by Ivan.Sokolov on 21.11.2021.
 */ 

public with sharing class CaseTriggerTestFactory {
    public static List<Case> generateCasesWithCountryAndStatus(Integer numCases, Country__c country, String status){
        List<Case> cases = new List<Case>();
        for (Integer i=0; i<numCases; i++){
            cases.add(
                    new Case(
                            Subject='Test1',
                            Country__c = country.Id,
                            Status = status)
            );
        }
        return cases;
    }

    public static void updateCasesStatus(List<Case> cases, String status){
        for (Case c : cases) {
            c.Status = status;
        }
    }

    public static Country__c getCountry(String countryName){
        Country__c country = [SELECT Id, ClosedCases__c, SuccessMessage__c FROM Country__c WHERE Name = :countryName LIMIT 1];
        return country;
    }

    public static Integer countCasesWithSuccessMessage(String message){
        return [SELECT COUNT() FROM Case WHERE SuccessMessage__c = :message];
    }
}