src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case’s Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SuccessMessage__c</fullName>
        <label>Received Success Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <description>Custom class from HW 9</description>
    <fields>
        <fullName>ClosedCases__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Closed Cases</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SuccessMessage__c</fullName>
        <label>Success Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CaseTriggerTest.cls
/**
 * Created by Ivan.Sokolov on 21.11.2021.
 */

@IsTest
public class CaseTriggerTest {
    @IsTest(SeeAllData=true)
    static void testBeforeInsert() {
        // prepare data
        Country__c testCountry = CaseTriggerTestFactory.getCountry('Albania');
        Integer existingCasesWithMessage = CaseTriggerTestFactory.countCasesWithSuccessMessage(testCountry.SuccessMessage__c);
        List<Case> newCases = CaseTriggerTestFactory.generateCasesWithCountryAndStatus(50, testCountry, 'New');
        newCases.addAll(CaseTriggerTestFactory.generateCasesWithCountryAndStatus(150, testCountry, 'Closed'));
        Integer currentClosed = (Integer)testCountry.ClosedCases__c;

        Test.startTest();
        insert newCases;
        Test.stopTest();

        // validate
        testCountry = CaseTriggerTestFactory.getCountry('Albania');
        List<Case> insertedCases = [SELECT Id FROM Case WHERE SuccessMessage__c = :testCountry.SuccessMessage__c];
        System.assert(currentClosed + 150 == testCountry.ClosedCases__c);
        System.assert(existingCasesWithMessage + 150 == insertedCases.size());
    }

    @IsTest(SeeAllData=true)
    static void testBeforeUpdate() {
        // prepare data
        Country__c testCountry = CaseTriggerTestFactory.getCountry('Albania');
        Integer existingCasesWithMessage = CaseTriggerTestFactory.countCasesWithSuccessMessage(testCountry.SuccessMessage__c);
        List<Case> newCases = CaseTriggerTestFactory.generateCasesWithCountryAndStatus(200, testCountry, 'New');
        insert newCases;
        Integer currentClosed = (Integer)testCountry.ClosedCases__c;
        CaseTriggerTestFactory.updateCasesStatus(newCases, 'Closed');

        Test.startTest();
        update newCases;
        Test.stopTest();

        // validate
        testCountry = CaseTriggerTestFactory.getCountry('Albania');
        List<Case> updatedCases = [SELECT Id FROM Case WHERE SuccessMessage__c = :testCountry.SuccessMessage__c];
        System.assert(currentClosed + 200 == testCountry.ClosedCases__c);
        System.assert(existingCasesWithMessage + 200 == updatedCases.size());
    }
}