src/objects/Diary__c.object
<CustomObject>
    <description>For Diary Notes LWC component</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Diaries</relationshipLabel>
        <relationshipName>Diaries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Created_Date__c</fullName>
        <label>Created Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Note__c</fullName>
        <label>Note</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Diary</label>
    <nameField>
        <label>Diary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Diaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DiaryController.cls
/**
 * Created by Ivan.Sokolov on 14.12.2021.
 */

public with sharing class DiaryController {
    @AuraEnabled(Cacheable=true)
    public static List<Diary__c> getDiaryNotesByContactId(Id contactId){
        return [SELECT Id, Created_Date__c, Note__c FROM Diary__c WHERE Contact__c =:contactId];
    }

    @AuraEnabled
    public static void addDiaryNote(Id contactId, String note){
        Date createdDate = System.Date.today();
        insert new Diary__c(
                Contact__c=contactId,
                Note__c=note,
                Created_Date__c=createdDate);
    }
}