src/objects/Notification__c.object
<CustomObject>
    <fields>
        <fullName>Notification_Message__c</fullName>
        <label>Notification Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Notification</label>
    <nameField>
        <label>Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ObjectNotificationSender.cls
/**
 * Created by Ivan.Sokolov on 26.12.2021.
 */

public with sharing class ObjectNotificationSender implements NotificationSender {

    public void sendNotification(String notificationMessage){
        Notification__c notification = new Notification__c(Notification_Message__c=notificationMessage);
        try{
            insert notification;
        }
        catch (Exception e){
            System.debug('The following errors occurred: ' + e.getMessage());
        }
    }

}